# Generated by Django 4.2.7 on 2024-02-12 10:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("questions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="question",
            field=models.TextField(null=True),
        ),
    ]
